// Base category pool for Words mode
// Each category has a unique key, a display name, and a large list of words
// Keep words short and simple for small cells

export const CATEGORY_POOLS = [
  {
    key: "colors",
    name: "Colors",
    words: [
      "red",
      "blue",
      "green",
      "yellow",
      "purple",
      "orange",
      "pink",
      "brown",
      "black",
      "white",
      "gray",
      "beige",
      "teal",
      "navy",
      "maroon",
      "cyan",
      "violet",
      "indigo",
      "magenta",
      "amber",
      "coral",
      "crimson",
      "khaki",
    ],
  },
  {
    key: "animals",
    name: "Animals",
    words: [
      "dog",
      "cat",
      "lion",
      "tiger",
      "bear",
      "elephant",
      "zebra",
      "giraffe",
      "monkey",
      "horse",
      "cow",
      "sheep",
      "goat",
      "pig",
      "wolf",
      "fox",
      "deer",
      "moose",
      "bison",
      "panda",
      "koala",
      "sloth",
      "otter",
    ],
  },
  {
    key: "fruits",
    name: "Fruits",
    words: [
      "apple",
      "banana",
      "orange",
      "grape",
      "pear",
      "peach",
      "plum",
      "kiwi",
      "mango",
      "papaya",
      "melon",
      "cherry",
      "lemon",
      "lime",
      "fig",
      "berry",
      "apricot",
      "guava",
      "lychee",
      "date",
      "raisin",
      "coconut",
      "passion",
    ],
  },
  {
    key: "shapes",
    name: "Shapes",
    words: [
      "circle",
      "square",
      "triangle",
      "rectangle",
      "diamond",
      "oval",
      "star",
      "heart",
      "hexagon",
      "pentagon",
      "octagon",
      "cube",
      "sphere",
      "cone",
      "pyramid",
      "cylinder",
      "prism",
      "arc",
      "crescent",
      "trapezoid",
      "rhombus",
    ],
  },
  {
    key: "vehicles",
    name: "Vehicles",
    words: [
      "car",
      "bus",
      "train",
      "plane",
      "boat",
      "truck",
      "bike",
      "scooter",
      "subway",
      "ship",
      "helicopter",
      "taxi",
      "van",
      "ferry",
      "yacht",
      "jet",
      "tram",
      "cart",
      "wagon",
      "rocket",
      "blimp",
      "canoe",
      "kayak",
    ],
  },
  {
    key: "kitchen",
    name: "Kitchen",
    words: [
      "spoon",
      "fork",
      "knife",
      "plate",
      "bowl",
      "cup",
      "pan",
      "pot",
      "whisk",
      "grater",
      "kettle",
      "ladle",
      "spatula",
      "tongs",
      "peeler",
      "strainer",
      "sieve",
      "colander",
      "skillet",
      "wok",
      "mug",
      "pitcher",
      "jug",
    ],
  },
  {
    key: "instruments",
    name: "Instruments",
    words: [
      "piano",
      "guitar",
      "violin",
      "drum",
      "flute",
      "trumpet",
      "harp",
      "cello",
      "saxophone",
      "clarinet",
      "tuba",
      "banjo",
      "ukulele",
      "oboe",
      "bassoon",
      "xylophone",
      "accordion",
      "harmonica",
      "organ",
      "lyre",
      "mandolin",
      "sitar",
    ],
  },
  {
    key: "clothing",
    name: "Clothing",
    words: [
      "shirt",
      "pants",
      "dress",
      "skirt",
      "coat",
      "jacket",
      "hat",
      "scarf",
      "gloves",
      "shoes",
      "socks",
      "belt",
      "tie",
      "vest",
      "sweater",
      "hoodie",
      "shorts",
      "jeans",
      "blazer",
      "cardigan",
      "mittens",
      "boots",
      "sandals",
    ],
  },
  {
    key: "emotions",
    name: "Emotions",
    words: [
      "happy",
      "sad",
      "angry",
      "joyful",
      "scared",
      "brave",
      "calm",
      "nervous",
      "proud",
      "shy",
      "bored",
      "excited",
      "worried",
      "anxious",
      "jealous",
      "grateful",
      "hopeful",
      "lonely",
      "content",
      "relaxed",
      "tense",
      "eager",
    ],
  },
  {
    key: "birds",
    name: "Birds",
    words: [
      "sparrow",
      "eagle",
      "robin",
      "crow",
      "owl",
      "duck",
      "goose",
      "swan",
      "parrot",
      "falcon",
      "pigeon",
      "hawk",
      "heron",
      "pelican",
      "stork",
      "crane",
      "raven",
      "magpie",
      "finch",
      "wren",
      "jay",
      "tern",
      "gull",
    ],
  },
  {
    key: "vegetables",
    name: "Vegetables",
    words: [
      "carrot",
      "onion",
      "broccoli",
      "lettuce",
      "spinach",
      "pepper",
      "tomato",
      "cabbage",
      "pea",
      "bean",
      "garlic",
      "cucumber",
      "celery",
      "radish",
      "turnip",
      "beet",
      "leek",
      "zucchini",
      "squash",
      "kale",
      "chard",
      "corn",
    ],
  },
  {
    key: "appliances",
    name: "Appliances",
    words: [
      "toaster",
      "fridge",
      "oven",
      "microwave",
      "blender",
      "kettle",
      "washer",
      "dryer",
      "iron",
      "mixer",
      "heater",
      "fan",
      "vacuum",
      "freezer",
      "stove",
      "dishwasher",
      "cooker",
      "steamer",
      "fryer",
      "juicer",
      "grinder",
      "roaster",
    ],
  },
  {
    key: "professions",
    name: "Professions",
    words: [
      "doctor",
      "nurse",
      "teacher",
      "lawyer",
      "chef",
      "pilot",
      "artist",
      "actor",
      "engineer",
      "writer",
      "farmer",
      "judge",
      "dentist",
      "surgeon",
      "therapist",
      "analyst",
      "designer",
      "architect",
      "musician",
      "reporter",
      "editor",
      "clerk",
    ],
  },
  {
    key: "fabrics",
    name: "Fabrics",
    words: [
      "cotton",
      "silk",
      "wool",
      "linen",
      "denim",
      "leather",
      "velvet",
      "satin",
      "polyester",
      "nylon",
      "suede",
      "fleece",
      "tweed",
      "canvas",
      "corduroy",
      "rayon",
      "chiffon",
      "organza",
      "taffeta",
      "muslin",
      "jersey",
      "spandex",
    ],
  },
  {
    key: "sports",
    name: "Sports",
    words: [
      "soccer",
      "tennis",
      "golf",
      "boxing",
      "rugby",
      "cricket",
      "hockey",
      "basketball",
      "volleyball",
      "swimming",
      "skiing",
      "baseball",
      "softball",
      "bowling",
      "archery",
      "fencing",
      "judo",
      "karate",
      "cycling",
      "running",
      "surfing",
      "skating",
      "diving",
    ],
  },
  {
    key: "cities",
    name: "Cities",
    words: [
      "paris",
      "london",
      "tokyo",
      "madrid",
      "rome",
      "miami",
      "sydney",
      "berlin",
      "dubai",
      "toronto",
      "seoul",
      "moscow",
      "cairo",
      "mumbai",
      "beijing",
      "vienna",
      "prague",
      "oslo",
      "athens",
      "lisbon",
      "warsaw",
      "dublin",
      "lima",
    ],
  },
  {
    key: "tools",
    name: "Tools",
    words: [
      "hammer",
      "screwdriver",
      "wrench",
      "saw",
      "drill",
      "pliers",
      "chisel",
      "level",
      "file",
      "tape",
      "clamp",
      "mallet",
      "axe",
      "shovel",
      "rake",
      "hoe",
      "spade",
      "trowel",
      "pickaxe",
      "crowbar",
      "vise",
      "anvil",
      "grinder",
    ],
  },
  {
    key: "elements",
    name: "Elements",
    words: [
      "oxygen",
      "hydrogen",
      "carbon",
      "nitrogen",
      "iron",
      "gold",
      "silver",
      "neon",
      "helium",
      "sodium",
      "calcium",
      "copper",
      "zinc",
      "lead",
      "tin",
      "mercury",
      "nickel",
      "cobalt",
      "sulfur",
      "chlorine",
      "iodine",
      "argon",
    ],
  },
  {
    key: "objects",
    name: "Objects",
    words: [
      "chair",
      "table",
      "lamp",
      "clock",
      "phone",
      "book",
      "pen",
      "bottle",
      "key",
      "wallet",
      "mirror",
      "bag",
      "watch",
      "camera",
      "radio",
      "remote",
      "glasses",
      "candle",
      "vase",
      "frame",
      "pillow",
      "blanket",
      "rug",
    ],
  },
  {
    key: "nature",
    name: "Nature",
    words: [
      "river",
      "mountain",
      "forest",
      "desert",
      "ocean",
      "lake",
      "valley",
      "island",
      "cliff",
      "beach",
      "field",
      "canyon",
      "swamp",
      "marsh",
      "plain",
      "plateau",
      "volcano",
      "glacier",
      "dune",
      "cave",
      "waterfall",
      "stream",
    ],
  },
  {
    key: "insects",
    name: "Insects",
    words: [
      "ant",
      "bee",
      "butterfly",
      "moth",
      "beetle",
      "fly",
      "spider",
      "wasp",
      "cricket",
      "grasshopper",
      "dragonfly",
      "ladybug",
      "mantis",
      "roach",
      "termite",
      "flea",
      "tick",
      "mosquito",
      "locust",
      "cicada",
      "firefly",
      "gnat",
    ],
  },
  {
    key: "fish",
    name: "Fish",
    words: [
      "salmon",
      "tuna",
      "trout",
      "cod",
      "bass",
      "shark",
      "ray",
      "eel",
      "catfish",
      "pike",
      "perch",
      "carp",
      "flounder",
      "halibut",
      "sardine",
      "anchovy",
      "herring",
      "mackerel",
      "snapper",
      "grouper",
      "barracuda",
      "marlin",
    ],
  },
  {
    key: "reptiles",
    name: "Reptiles",
    words: [
      "snake",
      "lizard",
      "turtle",
      "tortoise",
      "crocodile",
      "alligator",
      "iguana",
      "gecko",
      "chameleon",
      "skink",
      "python",
      "cobra",
      "viper",
      "boa",
      "adder",
      "dragon",
      "monitor",
      "caiman",
      "anole",
      "komodo",
      "rattlesnake",
      "basilisk",
    ],
  },
  {
    key: "desserts",
    name: "Desserts",
    words: [
      "cake",
      "pie",
      "cookie",
      "brownie",
      "pudding",
      "tart",
      "mousse",
      "custard",
      "parfait",
      "sundae",
      "sorbet",
      "gelato",
      "truffle",
      "fudge",
      "praline",
      "macaron",
      "eclair",
      "donut",
      "muffin",
      "scone",
      "tiramisu",
      "crepe",
      "waffle",
    ],
  },
  {
    key: "drinks",
    name: "Drinks",
    words: [
      "water",
      "juice",
      "coffee",
      "tea",
      "milk",
      "soda",
      "cola",
      "lemonade",
      "smoothie",
      "shake",
      "cocoa",
      "cider",
      "wine",
      "beer",
      "punch",
      "nectar",
      "tonic",
      "espresso",
      "latte",
      "mocha",
      "chai",
      "matcha",
      "kombucha",
    ],
  },
  {
    key: "flowers",
    name: "Flowers",
    words: [
      "rose",
      "lily",
      "tulip",
      "daisy",
      "orchid",
      "sunflower",
      "violet",
      "iris",
      "peony",
      "dahlia",
      "poppy",
      "lotus",
      "carnation",
      "jasmine",
      "lavender",
      "hibiscus",
      "daffodil",
      "azalea",
      "magnolia",
      "marigold",
      "zinnia",
      "pansy",
    ],
  },
  {
    key: "trees",
    name: "Trees",
    words: [
      "oak",
      "pine",
      "maple",
      "birch",
      "willow",
      "cedar",
      "elm",
      "ash",
      "spruce",
      "fir",
      "redwood",
      "cypress",
      "poplar",
      "beech",
      "walnut",
      "cherry",
      "apple",
      "pear",
      "palm",
      "bamboo",
      "sequoia",
      "mahogany",
      "teak",
    ],
  },
  {
    key: "weather",
    name: "Weather",
    words: [
      "sunny",
      "cloudy",
      "rainy",
      "snowy",
      "windy",
      "foggy",
      "stormy",
      "humid",
      "dry",
      "hot",
      "cold",
      "warm",
      "cool",
      "freezing",
      "mild",
      "breezy",
      "drizzly",
      "hazy",
      "misty",
      "icy",
      "sleet",
      "thunder",
      "lightning",
    ],
  },
  {
    key: "furniture",
    name: "Furniture",
    words: [
      "sofa",
      "couch",
      "desk",
      "bench",
      "stool",
      "cabinet",
      "dresser",
      "wardrobe",
      "shelf",
      "bookcase",
      "ottoman",
      "recliner",
      "loveseat",
      "armchair",
      "futon",
      "nightstand",
      "credenza",
      "buffet",
      "sideboard",
      "vanity",
      "console",
      "hutch",
    ],
  },
  {
    key: "hobbies",
    name: "Hobbies",
    words: [
      "reading",
      "writing",
      "painting",
      "drawing",
      "cooking",
      "baking",
      "sewing",
      "knitting",
      "fishing",
      "hiking",
      "camping",
      "dancing",
      "singing",
      "gaming",
      "puzzles",
      "chess",
      "yoga",
      "pottery",
      "crafts",
      "gardening",
      "woodwork",
      "travel",
    ],
  },
  {
    key: "countries",
    name: "Countries",
    words: [
      "france",
      "spain",
      "italy",
      "germany",
      "japan",
      "china",
      "india",
      "brazil",
      "mexico",
      "canada",
      "egypt",
      "greece",
      "sweden",
      "norway",
      "finland",
      "poland",
      "russia",
      "turkey",
      "korea",
      "thailand",
      "vietnam",
      "peru",
      "chile",
    ],
  },
  {
    key: "gemstones",
    name: "Gemstones",
    words: [
      "diamond",
      "ruby",
      "emerald",
      "sapphire",
      "topaz",
      "opal",
      "jade",
      "pearl",
      "amethyst",
      "garnet",
      "turquoise",
      "onyx",
      "quartz",
      "agate",
      "jasper",
      "aquamarine",
      "citrine",
      "peridot",
      "zircon",
      "moonstone",
      "amber",
      "coral",
    ],
  },
  {
    key: "office",
    name: "Office",
    words: [
      "stapler",
      "paper",
      "folder",
      "binder",
      "clipboard",
      "pencil",
      "eraser",
      "ruler",
      "scissors",
      "tape",
      "glue",
      "marker",
      "highlighter",
      "notepad",
      "calendar",
      "planner",
      "envelope",
      "stamp",
      "label",
      "tray",
      "organizer",
      "shredder",
    ],
  },
  {
    key: "school",
    name: "School",
    words: [
      "student",
      "teacher",
      "desk",
      "board",
      "chalk",
      "eraser",
      "notebook",
      "textbook",
      "backpack",
      "locker",
      "pencil",
      "crayon",
      "ruler",
      "compass",
      "calculator",
      "laptop",
      "tablet",
      "project",
      "homework",
      "test",
      "quiz",
      "lesson",
    ],
  },
  {
    key: "rooms",
    name: "Rooms",
    words: [
      "kitchen",
      "bedroom",
      "bathroom",
      "living",
      "dining",
      "garage",
      "basement",
      "attic",
      "closet",
      "hallway",
      "study",
      "office",
      "nursery",
      "laundry",
      "foyer",
      "pantry",
      "den",
      "library",
      "parlor",
      "mudroom",
      "sunroom",
      "patio",
    ],
  },
  {
    key: "seafood",
    name: "Seafood",
    words: [
      "shrimp",
      "crab",
      "lobster",
      "clam",
      "oyster",
      "mussel",
      "scallop",
      "squid",
      "octopus",
      "prawn",
      "crawfish",
      "crayfish",
      "snail",
      "conch",
      "abalone",
      "whelk",
      "cockle",
      "periwinkle",
      "urchin",
      "barnacle",
      "jellyfish",
      "starfish",
    ],
  },
  {
    key: "dairy",
    name: "Dairy",
    words: [
      "milk",
      "cheese",
      "butter",
      "cream",
      "yogurt",
      "ice cream",
      "whey",
      "curd",
      "cottage",
      "ricotta",
      "brie",
      "cheddar",
      "mozzarella",
      "parmesan",
      "feta",
      "gouda",
      "swiss",
      "provolone",
      "blue",
      "camembert",
      "mascarpone",
      "custard",
    ],
  },
  {
    key: "grains",
    name: "Grains",
    words: [
      "wheat",
      "rice",
      "corn",
      "oat",
      "barley",
      "rye",
      "millet",
      "quinoa",
      "sorghum",
      "spelt",
      "buckwheat",
      "amaranth",
      "teff",
      "farro",
      "bulgur",
      "couscous",
      "semolina",
      "polenta",
      "grits",
      "bran",
      "germ",
      "flour",
      "cereal",
    ],
  },
  {
    key: "toys",
    name: "Toys",
    words: [
      "doll",
      "ball",
      "puzzle",
      "blocks",
      "lego",
      "teddy",
      "train",
      "car",
      "truck",
      "airplane",
      "robot",
      "kite",
      "yoyo",
      "marbles",
      "cards",
      "dice",
      "spinner",
      "frisbee",
      "slinky",
      "playdough",
      "action",
      "board",
      "rattle",
    ],
  },
  {
    key: "materials",
    name: "Materials",
    words: [
      "wood",
      "metal",
      "plastic",
      "glass",
      "stone",
      "brick",
      "cement",
      "concrete",
      "marble",
      "granite",
      "clay",
      "ceramic",
      "porcelain",
      "rubber",
      "foam",
      "resin",
      "fiberglass",
      "plaster",
      "cardboard",
      "paper",
      "wax",
      "tar",
      "asphalt",
    ],
  },
  {
    key: "body",
    name: "Body Parts",
    words: [
      "head",
      "arm",
      "leg",
      "hand",
      "foot",
      "eye",
      "ear",
      "nose",
      "mouth",
      "neck",
      "shoulder",
      "elbow",
      "wrist",
      "knee",
      "ankle",
      "finger",
      "toe",
      "chest",
      "back",
      "stomach",
      "hip",
      "thigh",
      "calf",
    ],
  },
  {
    key: "verbs",
    name: "Actions",
    words: [
      "run",
      "jump",
      "walk",
      "swim",
      "climb",
      "fly",
      "dance",
      "sing",
      "talk",
      "read",
      "write",
      "draw",
      "paint",
      "eat",
      "drink",
      "sleep",
      "laugh",
      "cry",
      "smile",
      "think",
      "learn",
      "teach",
      "play",
    ],
  },
  {
    key: "time",
    name: "Time",
    words: [
      "second",
      "minute",
      "hour",
      "day",
      "week",
      "month",
      "year",
      "decade",
      "century",
      "morning",
      "noon",
      "afternoon",
      "evening",
      "night",
      "midnight",
      "dawn",
      "dusk",
      "twilight",
      "today",
      "tomorrow",
      "yesterday",
      "future",
      "past",
    ],
  },
  {
    key: "metals",
    name: "Metals",
    words: [
      "iron",
      "steel",
      "copper",
      "brass",
      "bronze",
      "aluminum",
      "tin",
      "lead",
      "zinc",
      "nickel",
      "silver",
      "gold",
      "platinum",
      "titanium",
      "chromium",
      "cobalt",
      "tungsten",
      "mercury",
      "magnesium",
      "alloy",
      "pewter",
      "solder",
    ],
  },
  {
    key: "garden",
    name: "Garden",
    words: [
      "seed",
      "soil",
      "plant",
      "flower",
      "tree",
      "bush",
      "grass",
      "weed",
      "vine",
      "moss",
      "fern",
      "hedge",
      "shrub",
      "compost",
      "mulch",
      "fertilizer",
      "hose",
      "spade",
      "rake",
      "trowel",
      "pot",
      "planter",
      "greenhouse",
    ],
  },
  {
    key: "space",
    name: "Space",
    words: [
      "sun",
      "moon",
      "star",
      "planet",
      "comet",
      "asteroid",
      "meteor",
      "galaxy",
      "nebula",
      "orbit",
      "rocket",
      "satellite",
      "shuttle",
      "station",
      "cosmos",
      "universe",
      "void",
      "eclipse",
      "crater",
      "mars",
      "venus",
      "jupiter",
      "saturn",
    ],
  },
  {
    key: "landmarks",
    name: "Landmarks",
    words: [
      "tower",
      "bridge",
      "statue",
      "monument",
      "pyramid",
      "temple",
      "cathedral",
      "palace",
      "castle",
      "fortress",
      "wall",
      "arch",
      "gate",
      "fountain",
      "obelisk",
      "dome",
      "spire",
      "plaza",
      "square",
      "park",
      "garden",
      "museum",
    ],
  },
  {
    key: "dance",
    name: "Dance Styles",
    words: [
      "ballet",
      "jazz",
      "tap",
      "salsa",
      "tango",
      "waltz",
      "swing",
      "rumba",
      "samba",
      "foxtrot",
      "cha-cha",
      "mambo",
      "disco",
      "breakdance",
      "hip-hop",
      "contemporary",
      "modern",
      "ballroom",
      "flamenco",
      "jive",
      "quickstep",
      "polka",
    ],
  },
  {
    key: "genres",
    name: "Music Genres",
    words: [
      "rock",
      "pop",
      "jazz",
      "blues",
      "country",
      "folk",
      "classical",
      "opera",
      "rap",
      "hip-hop",
      "reggae",
      "ska",
      "funk",
      "soul",
      "disco",
      "techno",
      "house",
      "ambient",
      "metal",
      "punk",
      "indie",
      "gospel",
      "swing",
    ],
  },
  {
    key: "farm",
    name: "Farm Animals",
    words: [
      "chicken",
      "rooster",
      "hen",
      "duck",
      "goose",
      "turkey",
      "cow",
      "bull",
      "calf",
      "pig",
      "sow",
      "horse",
      "mare",
      "foal",
      "sheep",
      "lamb",
      "goat",
      "kid",
      "donkey",
      "mule",
      "llama",
      "alpaca",
      "rabbit",
    ],
  },
  {
    key: "spices",
    name: "Spices",
    words: [
      "pepper",
      "salt",
      "cinnamon",
      "ginger",
      "nutmeg",
      "clove",
      "cumin",
      "paprika",
      "turmeric",
      "saffron",
      "cardamom",
      "coriander",
      "fennel",
      "mustard",
      "oregano",
      "basil",
      "thyme",
      "rosemary",
      "sage",
      "dill",
      "parsley",
      "mint",
      "bay",
    ],
  },
  {
    key: "containers",
    name: "Containers",
    words: [
      "box",
      "jar",
      "can",
      "crate",
      "barrel",
      "bucket",
      "basket",
      "bin",
      "chest",
      "trunk",
      "case",
      "carton",
      "package",
      "sack",
      "pouch",
      "bag",
      "tub",
      "vat",
      "tank",
      "canister",
      "container",
      "vessel",
      "drum",
    ],
  },
  {
    key: "buildings",
    name: "Buildings",
    words: [
      "house",
      "apartment",
      "condo",
      "mansion",
      "cottage",
      "cabin",
      "villa",
      "bungalow",
      "townhouse",
      "duplex",
      "skyscraper",
      "tower",
      "mall",
      "store",
      "shop",
      "restaurant",
      "cafe",
      "hotel",
      "motel",
      "inn",
      "hospital",
      "school",
    ],
  },
  {
    key: "fabrics2",
    name: "Textiles",
    words: [
      "burlap",
      "chenille",
      "damask",
      "gingham",
      "houndstooth",
      "paisley",
      "plaid",
      "brocade",
      "calico",
      "cambric",
      "cashmere",
      "challis",
      "crepe",
      "eyelet",
      "gabardine",
      "gauze",
      "jacquard",
      "knit",
      "lace",
      "sateen",
      "tulle",
      "voile",
    ],
  },
  {
    key: "occupations2",
    name: "Jobs",
    words: [
      "waiter",
      "cashier",
      "janitor",
      "guard",
      "clerk",
      "manager",
      "director",
      "supervisor",
      "agent",
      "broker",
      "consultant",
      "advisor",
      "assistant",
      "coordinator",
      "secretary",
      "receptionist",
      "operator",
      "technician",
      "specialist",
      "inspector",
      "auditor",
      "accountant",
      "analyst",
    ],
  },
  {
    key: "pets",
    name: "Pets",
    words: [
      "dog",
      "cat",
      "hamster",
      "gerbil",
      "guinea",
      "rabbit",
      "ferret",
      "mouse",
      "rat",
      "bird",
      "parrot",
      "canary",
      "finch",
      "fish",
      "goldfish",
      "turtle",
      "lizard",
      "snake",
      "frog",
      "hermit",
      "chinchilla",
      "hedgehog",
      "sugar",
    ],
  },
  {
    key: "herbs",
    name: "Herbs",
    words: [
      "basil",
      "thyme",
      "rosemary",
      "sage",
      "oregano",
      "parsley",
      "cilantro",
      "dill",
      "mint",
      "chives",
      "tarragon",
      "marjoram",
      "fennel",
      "lavender",
      "lemongrass",
      "chamomile",
      "anise",
      "bay",
      "chervil",
      "savory",
      "sorrel",
      "verbena",
    ],
  },
  {
    key: "ocean",
    name: "Ocean Life",
    words: [
      "whale",
      "dolphin",
      "seal",
      "walrus",
      "manatee",
      "otter",
      "shark",
      "ray",
      "jellyfish",
      "octopus",
      "squid",
      "coral",
      "anemone",
      "starfish",
      "urchin",
      "crab",
      "lobster",
      "shrimp",
      "clam",
      "oyster",
      "seahorse",
      "turtle",
      "penguin",
    ],
  },
  {
    key: "tech",
    name: "Technology",
    words: [
      "computer",
      "laptop",
      "tablet",
      "phone",
      "smartphone",
      "monitor",
      "keyboard",
      "mouse",
      "printer",
      "scanner",
      "router",
      "modem",
      "server",
      "drive",
      "disk",
      "cable",
      "charger",
      "adapter",
      "speaker",
      "headset",
      "webcam",
      "microphone",
      "screen",
    ],
  },
];

// Buckets for similarity tiers
export const TIER_BUCKETS = {
  EASY: [
    "colors",
    "animals",
    "fruits",
    "shapes",
    "vehicles",
    "clothing",
    "objects",
    "flowers",
    "pets",
    "toys",
    "body",
    "verbs",
    "time",
  ],
  MEDIUM: [
    "kitchen",
    "instruments",
    "emotions",
    "tools",
    "sports",
    "hobbies",
    "weather",
    "furniture",
    "rooms",
    "office",
    "school",
    "dance",
    "genres",
    "tech",
    "containers",
  ],
  HARD: [
    "birds",
    "vegetables",
    "appliances",
    "elements",
    "cities",
    "insects",
    "fish",
    "reptiles",
    "desserts",
    "drinks",
    "trees",
    "countries",
    "gemstones",
    "seafood",
    "dairy",
    "grains",
    "materials",
    "metals",
    "garden",
    "space",
    "buildings",
  ],
  EXTREME: [
    "professions",
    "fabrics",
    "occupations2",
    "landmarks",
    "farm",
    "spices",
    "fabrics2",
    "herbs",
    "ocean",
    "nature",
  ],
};

export function getCategoryByKey(key) {
  return CATEGORY_POOLS.find((c) => c.key === key);
}
